apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-application
  description: my test application.
  # Example for optional annotations
  # annotations:
     github.com/project-slug: Finboconnect/test-application
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
